language: php
sudo: false

php:
  - 7.2
  - 7.3

env:
  matrix:
    - GENERIC=1
    
  global:
    - DEFAULT=1
  
matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: COVERAGE=1 DEFAULT=0

    - php: 7.3
      env: PHPCS=1 DEFAULT=0

    - php: 7.3
      env: PHPSTAN=1 DEFAULT=0

before_script:
  - composer self-update
  - composer global require hirak/prestissimo
  - composer install --prefer-dist --no-interaction
  - sh -c "if [ '$COVERALLS' = '1' ]; then mkdir -p build/logs; fi"
  - if [[ $TRAVIS_PHP_VERSION != 7.3 ]]; then phpenv config-rm xdebug.ini; fi
  - if [[ $PHPSTAN = 1 ]]; then composer stan-setup; fi

script:
  - vendor/bin/phpunit
  - if [[ $DEFAULT = 1 ]]; then composer test; fi
  - if [[ $COVERAGE = 1 ]]; then composer coverage-test; fi
  - if [[ $PHPCS = 1 ]]; then composer cs-check; fi
  - if [[ $PHPSTAN = 1 ]]; then composer stan; fi

after_success:
  - if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
